use_frameworks!

platform :ios, '9.0'

target 'qgNetworking_Example' do
  pod 'qgNetworking', :path => '../'

  target 'qgNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
